name: "github-action-auto-format"
description: "Run auto-formatting functionality for different aspects of a repo. (See scripts for details.)"
inputs:
  actions-files-checkout-path:
    description: 'The path to checkout the action scripts to at runtime'
    default: github-action-auto-format
    required: false
  script-names:
    description: "Name of script to be executed"
    required: true
  workflow-token:
    description: "token with `workflows` permission, for use in `github_format.sh` and PR creation steps"
    required: true
  bot-name:
    description: "username that will be used for writing new commits"
    required: false
    default: cloudpossebot

runs:
  using: "composite"
  steps:
    # Checkout repo
    - name: "Checkout commit"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.workflow-token }}

    # Assets that are checked out as part of an action are not mounted into subsequent container steps.
    # Therefore, we need to checkout the action code within the workdir to access it within the container steps.
    - name: "Checkout github-action-auto-format repo to load script locally on runner"
      uses: actions/checkout@v2
      with:
        repository: cloudposse/github-action-auto-format
        path: ${{ inputs.actions-files-checkout-path }}

    # Rebuild README.md and commit changes (if any) to the PR branch
    - name: "Rebuild README.md and commit changes (if any)"
      if: contains( inputs.script-names, 'readme_format' )
      uses: docker://cloudposse/build-harness:latest
      with:
        entrypoint: /github/workspace/${{ inputs.actions-files-checkout-path }}/readme_format.sh
      env:
        IGNORE_PATH: ${{ inputs.actions-files-checkout-path }}
        EVENT_TYPE: ${{ github.event_name }}
        BOT_NAME: ${{ inputs.bot-name }}

    # Add and commit standard .github files to the PR branch
    - name: "Add and commit standard .github files"
      if: contains( inputs.script-names, 'github_format' )
      uses: docker://cloudposse/build-harness:latest
      with:
        entrypoint: /github/workspace/${{ inputs.actions-files-checkout-path }}/github_format.sh
      env:
        IGNORE_PATH: ${{ inputs.actions-files-checkout-path }}
        EVENT_TYPE: ${{ github.event_name }}
        BOT_NAME: ${{ inputs.bot-name }}

    # Format Terraform files and commit changes (if any) to the PR branch
    - name: "Format Terraform files and commit changes (if any)"
      if: contains( inputs.script-names, 'terraform_format' )
      uses: docker://cloudposse/build-harness:latest
      with:
        entrypoint: /github/workspace/${{ inputs.actions-files-checkout-path }}/terraform_format.sh
      env:
        IGNORE_PATH: ${{ inputs.actions-files-checkout-path }}
        HOST_REPO: ${{ github.repository }}
        EVENT_TYPE: ${{ github.event_name }}
        BOT_NAME: ${{ inputs.bot-name }}

    # Cleanup checked out action files, since the pull request will add and commit all files indiscriminately
    - name: "Clean up github-action-auto-format repo"
      shell: bash
      run: |
        rm -r ${{ inputs.actions-files-checkout-path }}

    # If triggered by a pull request, push all committed changes
    - name: "Push to pre-existing PR branch"
      if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
      shell: bash
      run: |
        # Prevent looping by not pushing changes in response to changes from cloudpossebot
        [[ "${{ github.event.sender.login }}" ==  "${{ inputs.bot-name }}" ]] || git push

    # If triggered by cron event or manually, create pull request for any committed changes
    - name: "Create pull request and PR branch"
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.workflow-token }}
        commit-message: Auto-format functionality (readme, .github files, and terraform formatting)
        title: Scheduled Auto-format
        body: |-
          This auto-generated PR could do any combination of the following - updating `README.md` based on changes to `README.yaml`,
          adding standard files from the `cloudposse/.github` repo to this repo's `.github` folder, and ensuring that the formatting
          of all Terraform files present in the repo is uniform.
        labels: automated pr
        branch: github-action-auto-format
