name: "auto-format"
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-format:
    if: (github.event.pull_request.head.repo.full_name == github.repository) && (github.event.pull_request.state == 'open')
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-format@main
      with:
        script-name: readme
    - uses: cloudposse/github-action-auto-format@main
      with:
        script-name: github_format
    - uses: cloudposse/github-action-auto-format@main
      with:
        script-name: terraform_format
