name: "auto-format"
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  format:
    if: (github.event.pull_request.head.repo.full_name == github.repository) && (github.event.pull_request.state == 'open')
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-format@main
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
        script-name: terraform
    - uses: cloudposse/github-action-auto-format@main
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
        script-name: readme
