name: "auto-format"
on:
  schedule:
    - cron: '18 17 * * *'
  workflow_dispatch:

jobs:
  auto-format:
    if: ( (github.event.pull_request.head.repo.full_name == github.repository) && (github.event.pull_request.state == 'open') ) || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-format@review-branch
      with:
        script-names: readme,github_format,terraform_format
        workflow-token: ${{ secrets.TOKEN_WITH_WORKFLOWS_PERMISSION }}
