name: "auto-format"
on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: '56 7 * * *'

jobs:
  auto-format:
    if: ( (github.event.pull_request.head.repo.full_name == github.repository) && (github.event.pull_request.state == 'open') ) || (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-format@review-branch
      with:
        script-name: readme
        token: ${{ secrets.TOKEN_WITH_WORKFLOWS_PERMISSION }}
    - uses: cloudposse/github-action-auto-format@review-branch
      with:
        script-name: github_format
        token: ${{ secrets.TOKEN_WITH_WORKFLOWS_PERMISSION }}
    - uses: cloudposse/github-action-auto-format@review-branch
      with:
        script-name: terraform_format
        token: ${{ secrets.TOKEN_WITH_WORKFLOWS_PERMISSION }}
